<?php

use Illuminate\Database\Seeder;

class CourseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('course')->delete();

        $data = [
            [
                'major_id' => 1,
                'courseName' => 'Cellular Biology',
                'courseName_v' => 'Sinh học tế bào',
                'courseCode' => 'BIO1.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Genetics',
                'courseName_v' => 'Di truyền học',
                'courseCode' => 'BIO1.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'General Chemmistry I',
                'courseName_v' => 'Hóa đại cương I',
                'courseCode' => 'CHEM1.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Organic Chemistry',
                'courseName_v' => 'Hóa hữu cơ',
                'courseCode' => 'CHEM1.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'General Chemistry II',
                'courseName_v' => 'Hóa đại cương II',
                'courseCode' => 'CHEM1.5',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Practical Chemistry',
                'courseName_v' => 'Thực hành hóa',
                'courseCode' => 'CHEM1.6',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Basic programming',
                'courseName_v' => 'Lập trình cơ bản',
                'courseCode' => 'ICT1.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Introduction to Informatics',
                'courseName_v' => 'Tin học cơ sở',
                'courseCode' => 'ICT1.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Linear Algebra',
                'courseName_v' => 'Đại số tuyến tính',
                'courseCode' => 'MATH1.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Calculus I',
                'courseName_v' => 'Giải tích I',
                'courseCode' => 'MATH1.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Calculus II',
                'courseName_v' => 'Giải tích II',
                'courseCode' => 'MATH1.5',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Mechanics and Thermodynamics',
                'courseName_v' => 'Cơ học và nhiệt động học',
                'courseCode' => 'PHYS1.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Electromagnetism',
                'courseName_v' => 'Điện từ trường',
                'courseCode' => 'PHYS1.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Optics and Introduction to Quantum mechanics',
                'courseName_v' => 'Quang học và giới thiệu về cơ học lượng tử',
                'courseCode' => 'PHYS1.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Practical Physics',
                'courseName_v' => 'Thực hành vật lý',
                'courseCode' => 'PHYS1.5',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Introduction to Science in English',
                'courseName_v' => 'Tiếng Anh khoa học',
                'courseCode' => 'EN1.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Basic English Reading',
                'courseName_v' => 'Kỹ năng đọc cơ bản',
                'courseCode' => 'EN1.5',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 1,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Basic English Writing',
                'courseName_v' => 'Kỹ năng viết cơ bản',
                'courseCode' => 'EN1.6',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Basic English Listening',
                'courseName_v' => 'Kỹ năng nghe cơ bản',
                'courseCode' => 'EN1.7',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 1,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Basic English Speaking',
                'courseName_v' => 'Kỹ năng nói cơ bản',
                'courseCode' => 'EN1.8',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Presentation Skills',
                'courseName_v' => 'Kỹ năng thuyết trình',
                'courseCode' => 'EN2.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Listening and Note-taking Skills',
                'courseName_v' => 'Kỹ năng nghe và ghi chú',
                'courseCode' => 'EN2.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Academic Writing Skills',
                'courseName_v' => 'Kỹ năng viết học thuật',
                'courseCode' => 'EN2.3',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 2,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Law on Science and Technology of Vietnam',
                'courseName_v' => 'Luật Khoa học và Công nghệ Việt Nam',
                'courseCode' => 'MS1.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 1,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 1,
                'courseName' => 'Foundation of Economics',
                'courseName_v' => 'Kinh tế học đại cương',
                'courseCode' => 'MS1.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 1,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Analysis& Algebraic Structures',
                'courseName_v' => 'Giải tích và Cấu trúc Đại Số',
                'courseCode' => 'MATH2.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Algorithms And Data Structures',
                'courseName_v' => 'Cấu trúc dữ liệu và giải thuật',
                'courseCode' => 'ICT2.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Object-oriented Programming',
                'courseName_v' => 'Lập trình hướng đối tượng',
                'courseCode' => 'ICT2.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Signals And Systems',
                'courseName_v' => 'Tín hiệu và hệ thống',
                'courseCode' => 'ICT2.3',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Computer Architecture',
                'courseName_v' => 'Kiến trúc máy tính',
                'courseCode' => 'ICT2.4',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Discrete Mathematics',
                'courseName_v' => 'Toán rời rạc',
                'courseCode' => 'MATH2.3',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Numerical Methods',
                'courseName_v' => 'Phương pháp số học',
                'courseCode' => 'MATH2.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Basic Databases',
                'courseName_v' => 'Cơ sở dữ liệu',
                'courseCode' => 'ICT2.5',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Computer Networks',
                'courseName_v' => 'Mạng máy tính',
                'courseCode' => 'ICT2.6',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Software Engineering',
                'courseName_v' => 'Kỹ thuật phần mềm',
                'courseCode' => 'ICT2.7',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Operating Systems',
                'courseName_v' => 'Hệ điều hành',
                'courseCode' => 'ICT2.8',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Digital Signal Processing',
                'courseName_v' => 'Xử lý tín hiệu số',
                'courseCode' => 'ICT2.9',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Mobile Wireless Communication',
                'courseName_v' => 'Truyền thông không dây di động',
                'courseCode' => 'ICT2.10',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 2,
                'courseName' => 'French 2.1',
                'courseName_v' => 'Tiếng Pháp 2.1',
                'courseCode' => 'FR2.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 2,
                'courseName' => 'French 2.2',
                'courseName_v' => 'Tiếng Pháp 2.2',
                'courseCode' => 'FR2.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 4,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 2,
                'courseName' => 'Law on IP rights',
                'courseName_v' => 'Luật sở hữu trí tuệ',
                'courseCode' => 'MS2.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 1,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 2,
                'courseName' => 'Project Management',
                'courseName_v' => 'Quản lý dự án',
                'courseCode' => 'MS2.2',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 1,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
            [
                'major_id' => 3,
                'courseName' => 'Probabilities & Statistics',
                'courseName_v' => 'Xác suất thống kê',
                'courseCode' => 'MATH2.1',
                'summary' => 'Thís course provides knowledge about the organs in the cells',
                'totalHour' => 30,
                'lectureHour' => 21,
                'labHour' => 9,
                'ECTS' => 3,
                'created_at' => '2020-06-16 05:55:46',
                'updated_at' => '2020-06-26 08:32:33',
            ],
        ];
        DB::table('course')->insert($data);
    }
}
